### ISSUE TITLE
Stop action flow sequence execution when a condition is met

### ISSUE THREAD

**Issue by ssc2015** [Steveorevo/node-red-contrib-actionflows#10]
Is it possible to stop executing a sequence action flows (with the same prefix) once a condition is met and continue with next node in the main flow? Let us say there are 3 action flows with "test" prefix (test.one, test.two, test.three). My understanding is that all 3 of them will be executed in sequence based on priority. I am looking for a way to stop executing once a variable (e.g. msg.complete) is set, which can be set by any one of the action flows. If the test.one sets it, then it should immediately return to the main flow and should not execute test.two and test.three. Is there a way to accomplish this in the current version?

**Comment by Steveorevo** [comment]
There's a half dozen ways to achieve this. Use a conditional node to not invoke the action, or at the start of a given flow to not proceed. You could use a function node to write javascript to choose one output or the another that in turn invokes the action. ActionFlows itself has a javascript API that can be used to invoke defined flows; with logic you can conditionally not invoke them. May wish to use the slack channel for this as issues is not for support but bugs only please. :)
