### ISSUE TITLE
Problems using ActionFlows

### ISSUE THREAD

**Issue by gido83** [Steveorevo/node-red-contrib-actionflows#3]
Hi,

I've installed your node and imported the first basic flow.
It seems that it doesn't work.

actionflows v2.0
node-red v0.19.4
node.js v8.12.0

**Comment by Steveorevo** [comment]
Hi gidoUninova,
   Thanks for your feedback. It sounds like you are having an issue. I've been using it recently with the same specs and it appears to be working fine. Let's see if we can diagnose your issue; can you provide the following:

* Is there an error message? If so, what is it? (you can check the debug window and/or the CLI you started Node-RED with).
* Can you provide a screenshot of your issue? 
* Can you tell us what platform you are on Mac/Windows/Raspberry PI?

**Comment by gido83** [comment]
Hi Stephen,

I am using a windows virtual machine (windows 10) running on a MacOS host. The message that I receive whenever I try to run the basic flow (using the inject node button) is attached.

Cheers,

gido

**Comment by Steveorevo** [comment]
Oops. It looks like you are missing the attachment on this thread. Note: attachments via email probably doesn't work with GitHub. Please try again using your web browser and GitHub account to drag and drop the file in the comment reply window at:
```
https://github.com/Steveorevo/node-red-contrib-actionflows/issues/3#issuecomment-428312298
```

**Comment by gido83** [comment]
the attachment :)
![virtualbox_windows 10 64 dev_09_10_2018_19_58_49](https://user-images.githubusercontent.com/7241756/46693495-d8da0300-cc01-11e8-94d6-ac4f89672578.png)

**Comment by Steveorevo** [comment]
This issue appears to be Windows related. I'll see if I can reproduce it.

**Comment by gido83** [comment]
Actually I tried directly on my MAC and the error is the same (attached).

<img width="1680" alt="screen shot 2018-10-09 at 21 26 53" src="https://user-images.githubusercontent.com/7241756/46696645-894c0500-cc0a-11e8-99b2-075222f96ea6.png">

**Comment by Steveorevo** [comment]
Something appears a miss. I do not see this error on Mac or Pi; however you do appear to be on Node-RED 0.19.3 where as I am running 0.19.4 at least on Mac. However, I do not recall this issue during development (which ran under 0.19.X to 0.19.4).

<img width="640" alt="screen shot 2018-10-09 at 1 36 25 pm" src="https://user-images.githubusercontent.com/635399/46697069-a364f380-cbc8-11e8-8fc9-72e34e74d3cc.png">

**Comment by Steveorevo** [comment]
Another notable item is that it appears to be erring out early within 
```
/Users/admin/.node-red/node_modules/collections/shim-object.js
```

I do not have such a folder. This leads me to believe there is a conflict. Try the demo again with a clean .node-red folder. You can stop node-red and rename your current /Users/admin/.node-red to /Users/admin/.node-red-sav and restart Node-RED. A "clean" .node-red folder should be generated and you can install action flows and the demo script again. Please let me know if this does not resolve the issue.

**Comment by gido83** [comment]
Yes, you are right. It seems a conflict. I were able to run the example by using a clean .node-red folder.

**Comment by Steveorevo** [comment]
Do you happen to know the package that installed/is using collections/shim-object.js ? May want to contact the author to see if there is a resolution.
