### ISSUE TITLE
Problem with 0.20 version of NodeRed

### ISSUE THREAD

**Issue by gido83** [Steveorevo/node-red-contrib-actionflows#4]
Dear Stephen,

I upgrade my nodered to the LTS (0.20 version). Since I did that my action flows are not fully working. In particular, they works if action_in and action_out are in a tab (parent flow), however if I put them in a subflow they are not working. I noticed that in the LTS version of nodered, the developers made some enhancements to the subflows part, and I believe that this could have impact in your logic. Are you able to test the action flows with the LTS version of nodered and using subflows?

Cheers,

Giovanni

**Comment by Steveorevo** [comment]
Hi Giovanni, I'll try to make time to look into this. I haven't upgraded yet. To make things faster, can you upload/attach a basic flow that illustrates this issue?

**Comment by gido83** [comment]
Hi Stephen,

attached you can find a simple flow for testing.

Cheers,

Giovanni

[ActionFlowsExample.txt](https://github.com/Steveorevo/node-red-contrib-actionflows/files/3034689/ActionFlowsExample.txt)

**Comment by aabluedragon** [comment]
Hello @Steveorevo,

Please checkout the pull request with the fix the the issue above.
https://github.com/Steveorevo/node-red-contrib-actionflows/pull/5

Thanks,
Alon

**Comment by aabluedragon** [comment]
Hello @Steveorevo ,

Please check out the pull request regarding a fix for this issue https://github.com/Steveorevo/node-red-contrib-actionflows/pull/6

Thanks,
Alon

**Comment by aabluedragon** [comment]
Hello @Steveorevo ,

Please check out the following pull request for fixing this issue https://github.com/Steveorevo/node-red-contrib-actionflows/pull/7

Thanks,
Alon

**Comment by Steveorevo** [comment]
Hello @aabluedragon ,
  Looks good. Tested against @gidoUninova 's example and appears to resolve the issue for compatibility with Node-RED 0.20. Will push new release shortly. Thank you for contributing!

Regards,
Steve
